In [49]:
import math
import os
import random
import string

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from typing import Any
from graphviz import Digraph

os.chdir("/home/project")
%matplotlib inline

In [19]:
A = torch.nn.Linear(20, 30)
x = torch.randn(2, 20)
print(A(x).shape)
print(A.forward(x).shape)
A(x)

torch.Size([2, 30])
torch.Size([2, 30])


tensor([[-0.2558, -0.3071,  0.2085, -0.4553,  0.1427,  0.1148, -0.0282,  0.1995,
         -0.2040,  0.4150, -0.3980,  0.4788, -0.0854,  0.3569, -0.9645,  0.1672,
          0.2869,  0.5950, -0.4446,  0.0805,  0.1618, -0.2504,  0.2641, -0.1299,
          0.1458,  0.2906,  0.1374, -0.3642,  0.2721, -0.1877],
        [ 0.2401,  0.2756,  0.4716,  0.1437, -0.5999,  0.3556,  0.4561, -0.8795,
          0.7760, -0.3915,  0.8004, -0.9142,  0.3616, -0.5338,  0.6964,  1.6452,
          1.0959, -1.0724,  0.8340,  0.5345,  0.5786,  0.8510, -0.9939, -1.4520,
         -0.0224, -0.0102, -0.5686, -0.1509, -0.4323,  0.1814]],
       grad_fn=<AddmmBackward0>)

In [24]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(2, 4)
        self.linear2 = nn.Linear(4, 7)
        self.tanh = nn.Tanh()

    def forward(self, x):
        x = self.linear1(x)
        x = self.linear2(x)
        return self.tanh(x)


model = Model()

In [45]:
for name, param in model.named_parameters():
    print(name, param, type(param), param.size())

linear1.weight Parameter containing:
tensor([[ 0.5696, -0.6223],
        [ 0.5823,  0.5367],
        [ 0.2778, -0.3831],
        [ 0.4206, -0.3492]], requires_grad=True) <class 'torch.nn.parameter.Parameter'> torch.Size([4, 2])
linear1.bias Parameter containing:
tensor([ 0.3676,  0.1346, -0.6443,  0.5673], requires_grad=True) <class 'torch.nn.parameter.Parameter'> torch.Size([4])
linear2.weight Parameter containing:
tensor([[ 0.2786,  0.2662,  0.1046, -0.0018],
        [-0.4116, -0.1670,  0.2340, -0.0250],
        [ 0.3770, -0.3288,  0.3636, -0.0465],
        [ 0.0913,  0.4041,  0.1520,  0.2096],
        [ 0.3801,  0.0139, -0.1717, -0.2560],
        [-0.4974,  0.3775, -0.1229, -0.4550],
        [ 0.2996, -0.2543,  0.3079,  0.4933]], requires_grad=True) <class 'torch.nn.parameter.Parameter'> torch.Size([7, 4])
linear2.bias Parameter containing:
tensor([ 0.2421, -0.0756,  0.3588, -0.4582, -0.4747, -0.1955,  0.0873],
       requires_grad=True) <class 'torch.nn.parameter.Parameter'> torch.

In [48]:
for param in model.parameters():
    print(param, type(param), param.size())

Parameter containing:
tensor([[ 0.5696, -0.6223],
        [ 0.5823,  0.5367],
        [ 0.2778, -0.3831],
        [ 0.4206, -0.3492]], requires_grad=True) <class 'torch.nn.parameter.Parameter'> torch.Size([4, 2])
Parameter containing:
tensor([ 0.3676,  0.1346, -0.6443,  0.5673], requires_grad=True) <class 'torch.nn.parameter.Parameter'> torch.Size([4])
Parameter containing:
tensor([[ 0.2786,  0.2662,  0.1046, -0.0018],
        [-0.4116, -0.1670,  0.2340, -0.0250],
        [ 0.3770, -0.3288,  0.3636, -0.0465],
        [ 0.0913,  0.4041,  0.1520,  0.2096],
        [ 0.3801,  0.0139, -0.1717, -0.2560],
        [-0.4974,  0.3775, -0.1229, -0.4550],
        [ 0.2996, -0.2543,  0.3079,  0.4933]], requires_grad=True) <class 'torch.nn.parameter.Parameter'> torch.Size([7, 4])
Parameter containing:
tensor([ 0.2421, -0.0756,  0.3588, -0.4582, -0.4747, -0.1955,  0.0873],
       requires_grad=True) <class 'torch.nn.parameter.Parameter'> torch.Size([7])
